version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      envs:
        type: string
        default: "sphinx5,sphinx6,sphinx7,sphinx8,sphinxlatest"
    steps:
      - checkout
      - run: pip install --user tox
      - run:
          command: tox -e "<<parameters.envs>>"

jobs:
  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox
  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox
  py311:
    docker:
      - image: 'cimg/python:3.11'
    steps:
      - run-tox
  py312:
    docker:
      - image: 'cimg/python:3.12'
    steps:
      - run-tox
  py313:
    docker:
      - image: 'cimg/python:3.13'
    steps:
      - run-tox
  checks:
    docker:
      - image: 'cimg/python:3.13'
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e docs,lint

workflows:
  version: 2
  tests:
    jobs:
      - checks
      - py313
      - py312
      - py311
      - py310
      - py39
