version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "4,5,6,7,8,latest"
    steps:
      - checkout
      - run: pip install --user tox
      - run:
          command: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"

jobs:
  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39
  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox:
          version: py310
  py311:
    docker:
      - image: 'cimg/python:3.11'
    steps:
      - run-tox:
          version: py311
  py312:
    docker:
      - image: 'cimg/python:3.12'
    steps:
      - run-tox:
          version: py312
  py313:
    docker:
      - image: 'cimg/python:3.13'
    steps:
      - run-tox:
          version: py313
  checks:
    docker:
      - image: 'cimg/python:3.13'
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e docs,lint

workflows:
  version: 2
  tests:
    jobs:
      - checks
      - py313
      - py312
      - py311
      - py310
      - py39
